name: node-ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - node-*.*.x
    tags:
      - "node-*"

  pull_request:
    branches:
      - "*"

concurrency:
  # cancel jobs on PRs only
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: ubuntu-24.04
            arch: x86_64
          - runs-on: ubuntu-24.04-arm
            arch: arm64
          - runs-on: macos-13
            arch: x86_64
          - runs-on: macos-14
            arch: arm64
          - runs-on: windows-2022
            arch: x86_64
          - runs-on: windows-11-arm
            arch: arm64
    continue-on-error: true
    env:
      BUILDTYPE: "Release"

    defaults:
      run:
        working-directory: ./
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Initialize and Update Submodules
        shell: bash
        run: |
          echo "Fetching submodule HEADs..."
          git submodule sync --recursive
          echo "Updating submodules..."
          git -c core.longpaths=true submodule update --init --force --recursive || echo "Submodule update had some issues, continuing..."

      - name: Get OS Architecture
        if: runner.os == 'MacOS' || runner.os == 'Linux'
        run: uname -m

      - name: Install dependencies (MacOS)
        if: runner.os == 'MacOS'
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_NO_INSTALL_CLEANUP: 1
        run: |
          brew list ccache || brew install ccache
          brew list ninja || brew install ninja
          brew list pkg-config || brew install pkg-config
          brew list glfw || brew install glfw
          brew list libuv || brew install libuv

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ccache \
            ninja-build \
            pkg-config \
            xvfb \
            libcurl4-openssl-dev \
            libglfw3-dev \
            libuv1-dev \
            libjpeg-dev \
            libpng-dev \
            libwebp-dev
          /usr/sbin/update-ccache-symlinks

      - name: Use Node.js from nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: npm ci
        run: npm ci --ignore-scripts

      - name: Set up msvc dev cmd (Windows x64)
        if: runner.os == 'Windows' && matrix.arch == 'x86_64'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Set up msvc dev cmd (Windows ARM64)
        if: runner.os == 'Windows' && matrix.arch == 'arm64'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_arm64

      - name: Test VSCMD_ARG_TGT_ARCH Environment
        if: runner.os == 'Windows'
        run: |
          echo "VSCMD_ARG_TGT_ARCH=%VSCMD_ARG_TGT_ARCH%"
        shell: cmd
  
      - name: cmake version
        run: |
          cmake --version

      - name: Set up ccache (MacOS/Linux)
        if: runner.os == 'MacOS' || runner.os == 'Linux'
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ matrix.runs-on }}-${{ matrix.arch }}-${{ env.BUILDTYPE }}-${{ github.job }}-${{ github.ref }}-${{ github.sha }}-${{ github.head_ref }}
          restore-keys: |
            ${{ matrix.runs-on }}-${{ matrix.arch }}-${{ env.BUILDTYPE }}-${{ github.job }}-${{ github.ref }}-${{ github.sha }}
            ${{ matrix.runs-on }}-${{ matrix.arch }}-${{ env.BUILDTYPE }}-${{ github.job }}-${{ github.ref }}
            ${{ matrix.runs-on }}-${{ matrix.arch }}-${{ env.BUILDTYPE }}-${{ github.job }}

      - name: Set up ccache (Windows)
        if: runner.os == 'Windows'
        uses: hendrikmuhs/ccache-action@v1
        with:
          variant: "sccache"
          key: ${{ matrix.runs-on }}-${{ matrix.arch }}-${{ env.BUILDTYPE }}-${{ github.job }}-${{ github.ref }}-${{ github.sha }}-${{ github.head_ref }}
          restore-keys: |
            ${{ matrix.runs-on }}-${{ matrix.arch }}-${{ env.BUILDTYPE }}-${{ github.job }}-${{ github.ref }}-${{ github.sha }}
            ${{ matrix.runs-on }}-${{ matrix.arch }}-${{ env.BUILDTYPE }}-${{ github.job }}-${{ github.ref }}
            ${{ matrix.runs-on }}-${{ matrix.arch }}-${{ env.BUILDTYPE }}-${{ github.job }}

      - name: Build MapLibre-Native with CMake Presets
        run: |
          node ./scripts/build-maplibre.js

      - name: Cache cmake-node-module deps
        uses: actions/cache@v4
        with:
          path: maplibre-native/build
          key: ${{ runner.os }}-${{ runner.arch }}-cmake-node-module-deps

      - name: Run render tests on macOS
        if: runner.os == 'macOS'
        working-directory: maplibre-native
        run: set -o pipefail && ./build/mbgl-render-test-runner --manifestPath metrics/macos-xcode11-release-style.json

      - name: Upload render test artifacts (MacOS)
        if: runner.os == 'MacOS'
        uses: actions/upload-artifact@v4
        with:
          name: render-test-results
          path: metrics/macos-xcode11-release-style.html

      - name: Test (Linux)
        working-directory: maplibre-native/platform/node
        if: runner.os == 'Linux'
        run: xvfb-run --auto-servernum npm test

      - name: Test (MacOS)
        if: runner.os == 'MacOS'
        working-directory: maplibre-native/platform/node
        run: npm test

      - name: Test (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        working-directory: maplibre-native/platform/node
        env:
          LIBGL_ALWAYS_SOFTWARE: true
          GALLIUM_DRIVER: softpipe
        run: |
          Invoke-WebRequest https://github.com/pal1000/mesa-dist-win/releases/download/22.3.5/mesa3d-22.3.5-release-msvc.7z -OutFile mesa3d.7z
          & 'C:\Program Files\7-Zip\7z.exe' e -plib\node-v115 .\mesa3d.7z x64\opengl32.dll x64\libgallium_wgl.dll x64\libGLESv2.dll x64\libglapi.dll
          npm test

      # On PRs make sure that the npm package can be packaged.
      - name: Pack
        working-directory: maplibre-native/platform/node
        run: |
          npm pack --dry-run